Vagrant.require_version ">= 1.7.4"

HOSTS = [
    { :name => "orc-app1.test", :ip => "10.0.0.71", :cpus => "1",
      :mem => "256"  , :box => "bento/centos-7.3", 
    },
    { :name => "orc-app2.test", :ip => "10.0.0.72", :cpus => "1",
      :mem => "256"  , :box => "bento/centos-7.3", 
    },
    { :name => "orc-db.test", :ip => "10.0.0.73", :cpus => "1",
      :mem => "256"  , :box => "bento/centos-7.3", 
    },
]


Vagrant.configure(2) do |config|
    
    HOSTS.each do |opts|
        config.vm.define opts[:name] do |node|
            node.ssh.insert_key = false

            node.vm.hostname = opts[:name]
            node.vm.box      = opts[:box]
            node.ssh.insert_key = false
            node.vm.synced_folder "./data", "/vagrant", disabled: true

            node.vm.network "private_network", ip: opts[:ip]
            if (opts.has_key?(:ports))
                opts[:ports].each do |port|
                    node.vm.network "forwarded_port",
                        guest: port[:guest], host: port[:host]
                end
            end

            #node.vm.network "public_network", :bridge => 'en0: Wi-Fi (AirPort)'
            node.vm.network "public_network", :bridge => 'wlp1s0'
			
            node.vm.provider "virtualbox" do |vb|
                vb.name = opts[:name]
                vb.customize ["modifyvm", :id, "--memory", opts[:mem]]
				vb.customize ["modifyvm", :id, "--cpus", opts[:cpus]]
            end
            
            #node.vm.provision "shell", inline: <<-SHELL
            #    sudo yum upgrade
            #    sudo yum install net-tools
            #SHELL

        end
        
        

    end

end

